name: Deploy Cloud Function

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/856703908469/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-deployer@zeta-sky-458619-q6.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy function
        run: |
          gcloud functions deploy stock-summary \
            --gen2 \
            --runtime python311 \
            --trigger-http \
            --allow-unauthenticated \
            --region=europe-west1 \
            --entry-point=stock_summary \
            --memory=512Mi \
            --set-env-vars GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }},GEMINI_API_URL=${{ secrets.GEMINI_API_URL }},FINNHUB_API_TOKEN=${{ secrets.FINNHUB_API_TOKEN }},TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }},TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
            --source=.