name: Deploy Cloud Function

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/856703908469/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-deployer@zeta-sky-458619-q6.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy function
        run: |
          gcloud functions deploy stock-summary \
            --gen2 \
            --runtime python311 \
            --trigger-topic=stock-summary-topic \
            --region=europe-west1 \
            --entry-point=stock_summary \
            --memory=512Mi \
            --timeout=300 \
            --set-env-vars GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }},GEMINI_API_URL=${{ secrets.GEMINI_API_URL }},FINNHUB_API_TOKEN=${{ secrets.FINNHUB_API_TOKEN }},TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }},TELEGRAM_CRYPTO_CHAT_ID=${{ secrets.TELEGRAM_CRYPTO_CHAT_ID }},TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
            --source=.
      - name: Deploy crypto function
        run: |
          gcloud functions deploy crypto-summary \
            --gen2 \
            --runtime python311 \
            --region=europe-west1 \
            --entry-point=crypto_summary \
            --trigger-topic=crypto-summary-topic \
            --memory=512Mi \
            --timeout=300 \
            --set-env-vars GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }},GEMINI_API_URL=${{ secrets.GEMINI_API_URL }},FINNHUB_API_TOKEN=${{ secrets.FINNHUB_API_TOKEN }},TELEGRAM_CRYPTO_CHAT_ID=${{ secrets.TELEGRAM_CRYPTO_CHAT_ID }},TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
            --source=.

      - name: Deploy telegram webhook
        run: |
          gcloud functions deploy telegram-webhook \
            --gen2 \
            --runtime python311 \
            --region=europe-west1 \
            --entry-point=telegram_webhook \
            --trigger-http \
            --allow-unauthenticated \
            --memory=512Mi \
            --timeout=120 \
            --set-env-vars TELEGRAM_BOT_TOKEN_INTERACTIVE=${{ secrets.TELEGRAM_BOT_TOKEN_INTERACTIVE }},TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }} \
            --source=.